stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
    continueOnError: true
    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      ResourceGroup: 'mwtestrg'
      skuName: 'B1'
      skuCapacity: '1'
      sqlAdministratorLogin: 'superSecureLogin'
      sqlAdministratorLoginPassword: 'P455W0rd1234'
    steps:
    - task: NuGetToolInstaller@0

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        TargetFolder: '$(build.artifactstagingdirectory)'
        Contents: |
          Azure\**
          *\**.dacpac
          *.ps1
        OverWrite: true

    - task: PublishPipelineArtifact@0
      displayName: 'Publish artifact'
      inputs:
        artifactName: TechTalk
        targetPath: $(Build.ArtifactStagingDirectory)

- stage: DeployAcceptanceTest
  jobs:
  - template: Templates/stages.yml
    parameters:
      environment: 'AcceptanceTest'
      ResourceGroup: 'mwtestarg'
      sqlAdministratorLogin: 'superSecureLogin'
      sqlAdministratorLoginPassword: 'P455W0rd1234'

- stage: QA
  jobs:
  - template: Templates/stages.yml
    parameters:
      environment: 'QA'
      ResourceGroup: 'mwqarg'
      sqlAdministratorLogin: 'superSecureLogin'
      sqlAdministratorLoginPassword: '4dm1n15t4t0r1234'
