stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
    continueOnError: true
    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      ResourceGroup: 'mwtestrg'
      skuName: 'B1'
      skuCapacity: '1'
      sqlAdministratorLogin: 'superSecureLogin'
      sqlAdministratorLoginPassword: 'P455W0rd1234'
    steps:
    - task: NuGetToolInstaller@0

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        TargetFolder: '$(build.artifactstagingdirectory)'
        Contents: |
          Azure\**
          *\**.dacpac
        OverWrite: true

    - task: PublishPipelineArtifact@0
      displayName: 'Publish artifact'
      inputs:
        artifactName: TechTalk
        targetPath: $(Build.ArtifactStagingDirectory)

- stage: Deploy
  jobs:
  # track deployments on the environment
  - deployment: DeployWeb
    pool:
      vmImage: 'windows-latest'
  # creates an environment if it doesn’t exist
    variables:
      ResourceGroup: 'mwtestrg'
      skuName: 'B1'
      skuCapacity: '1'
      sqlAdministratorLogin: 'superSecureLogin'
      sqlAdministratorLoginPassword: 'P455W0rd1234'
      location: 'West Europe'
    environment: 'AcceptanceTest'
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
          - script: echo my first deployment
          - task: DownloadPipelineArtifact@0
            inputs:
              artifactName: 'TechTalk'
              downloadPath: $(System.DefaultWorkingDirectory)          
          - task: AzureResourceGroupDeployment@2
            displayName: 'Azure Deployment:Create Or Update Resource Group action on $(ResourceGroup)'
            inputs:
              azureSubscription: 'VSTS'
              resourceGroupName: $(ResourceGroup)
              location: 'West Europe'
              templateLocation: 'Linked artifact'
              csmFile: '$(System.DefaultWorkingDirectory)/Azure/template.json'
              overrideParameters: -skuName "$(skuName)" -skuCapacity "$(skuCapacity)" -sqlAdministratorLogin "$(sqlAdministratorLogin)" -sqlAdministratorLoginPassword "$(sqlAdministratorLoginPassword)" -location "$(location)"
              deploymentOutputs: armoutputs
          - task: keesschollaart.arm-outputs.arm-outputs.ARMOutputs@5
            displayName: 'ARM Outputs'
            inputs:
              ConnectedServiceNameARM: VSTS
              resourceGroupName: mwtestrg

 